import "../styles/globals.css"
import Link from "next/Link"

function Marketplace({Component,pageProps}){
  return(
    <div className="border-b p-6 bg-gradient-to-b from-purple-600 to-blue-600">
      <nav className="border-b p-6">
        <p className="text-4xl font-bold flex justify-center text-cyan-200">
          NFT Digital Art Marketplace
        </p>
        <div className="flex justify-center p-8">
          <Link href="/" className="mr-4 text-xl text-cyan-200">
            Home
          </Link>
          <Link href="/createNFT" className="mr-6 text-xl text-cyan-200">
            Sell Your NFTs
          </Link>
          <Link href="/myNFTs" className="mr-6 text-xl text-cyan-200">
            My NFTs
          </Link>
          <Link href="/dashboard" className="mr-6 text-xl text-cyan-200">
            Dashboard
          </Link>
        </div>
      </nav>
      <Component{...pageProps}/>
    </div>
  )
}
export default Marketplace


// // <Head>
// <title>Create Next App</title>
// <meta name="description" content="Generated by create next app" />
// <meta name="viewport" content="width=device-width, initial-scale=1" />
// <link rel="icon" href="/favicon.ico" />
// </Head>
// <main className={styles.main}>
// <div className={styles.description}>
//   <p>
//     Get started by editing&nbsp;
//     <code className={styles.code}>pages/index.js</code>
//   </p>
//   <div>
//     <a
//       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//       target="_blank"
//       rel="noopener noreferrer"
//     >
//       By{' '}
//       <Image
//         src="/vercel.svg"
//         alt="Vercel Logo"
//         className={styles.vercelLogo}
//         width={100}
//         height={24}
//         priority
//       />
//     </a>
//   </div>
// </div>

// <div className={styles.center}>
//   <Image
//     className={styles.logo}
//     src="/next.svg"
//     alt="Next.js Logo"
//     width={180}
//     height={37}
//     priority
//   />
//   <div className={styles.thirteen}>
//     <Image
//       src="/thirteen.svg"
//       alt="13"
//       width={40}
//       height={31}
//       priority
//     />
//   </div>
// </div>

// <div className={styles.grid}>
//   <a
//     href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//     className={styles.card}
//     target="_blank"
//     rel="noopener noreferrer"
//   >
//     <h2 className={inter.className}>
//       Docs <span>-&gt;</span>
//     </h2>
//     <p className={inter.className}>
//       Find in-depth information about Next.js features and&nbsp;API.
//     </p>
//   </a>

//   <a
//     href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//     className={styles.card}
//     target="_blank"
//     rel="noopener noreferrer"
//   >
//     <h2 className={inter.className}>
//       Learn <span>-&gt;</span>
//     </h2>
//     <p className={inter.className}>
//       Learn about Next.js in an interactive course with&nbsp;quizzes!
//     </p>
//   </a>

//   <a
//     href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//     className={styles.card}
//     target="_blank"
//     rel="noopener noreferrer"
//   >
//     <h2 className={inter.className}>
//       Templates <span>-&gt;</span>
//     </h2>
//     <p className={inter.className}>
//       Discover and deploy boilerplate example Next.js&nbsp;projects.
//     </p>
//   </a>

//   <a
//     href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//     className={styles.card}
//     target="_blank"
//     rel="noopener noreferrer"
//   >
//     <h2 className={inter.className}>
//       Deploy <span>-&gt;</span>
//     </h2>
//     <p className={inter.className}>
//       Instantly deploy your Next.js site to a shareable URL
//       with&nbsp;Vercel.
//     </p>
//   </a>
// </div>
// </main>